"""add new cols

Revision ID: 361f924ec5cc
Revises: ec43e5cd2d90
Create Date: 2025-08-05 19:11:56.981300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361f924ec5cc'
down_revision: Union[str, Sequence[str], None] = 'ec43e5cd2d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('superheroes', sa.Column('durability', sa.Integer(), nullable=False))
    op.add_column('superheroes', sa.Column('combat', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('superheroes', 'combat')
    op.drop_column('superheroes', 'durability')
    # ### end Alembic commands ###
